general.import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }

[window]
decorations = "None"
startup_mode = "Maximized"
dynamic_padding = true
blur = true
opacity = 0.75

